version: '3.4'

services:
  webui:
    image: ${DOCKER_REGISTRY-}webui
    build:
      context: .
      dockerfile: src/WebUI/Dockerfile
    environment:
      - "UseInMemoryDatabase=true"
      - "ConnectionStrings__DefaultConnection=Data Source=174.138.32.5;Initial Catalog=AwwCor-T;User ID=SA;Password=220977qQ;MultipleActiveResultSets=True"
    volumes:
      - ~/.aspnet/https:/https:ro

    restart: on-failure